package bot

// Daily_Morning is a collection of inspiring messages for starting the day right.
var Daily_Morning = []string{
	"Good morning! Waking up early and seizing the day already puts you ahead. Amazing things are waiting!",
	"What an incredible start! Your proactive approach to the morning sets the stage for a day filled with amazing achievements.",
	"Keep up this fantastic morning routine; your consistency in starting strong truly paves the way for success and incredible progress.",
	"Waking up with purpose is a fantastic effort! You've clearly channeled your energy into beginning the day right, which will lead to outstanding outcomes.",
	"Very well done on embracing the morning! Your early start is a powerful step towards making today truly remarkable and filled with accomplishments.",
	"You're doing wonderfully by kicking off your day with such drive; your focus this morning is truly impressive and will lead to great things.",
	"This is impressive progress right from the start! Each early action is a testament to your determination to make today amazing.",
	"Absolutely outstanding morning! The way you've begun your day speaks volumes about your capability and readiness for incredible achievements.",
	"Amazing start, truly inspiring! You've exceeded expectations by tackling the morning with such enthusiasm, setting yourself up for greatness.",
	"Your dedication shines through even in these early hours, making a real, tangible impact on how brilliantly your day will unfold.",
	"I couldn't imagine a better way to start the day! This is a perfect example of skillful morning preparation, thoughtful planning, and brilliant insight.",
	"Absolutely brilliant morning initiative! Your early actions are genuinely inspiring and pave the way for a day brimming with successes.",
	"A true master at starting the day right! Your expertise in morning productivity is clearly evident through your focused beginning.",
	"Every early step you take is forward progress, leading you closer to your goals with greater efficiency and effectiveness throughout the day.",
	"Simply superb start! The quality of your morning focus is exceptionally high, reflecting your commitment to excellence and a productive day.",
	"You've absolutely nailed the morning! This early focus is precise, effective, and beautifully executed, setting up a day of amazing achievements.",
	"Beyond expectations for a morning! You consistently deliver an incredible start that surpasses what's typical, adding immense value to your entire day.",
	"A shining example for everyone to follow in starting their day, demonstrating true excellence, leadership, and a profound understanding of productivity.",
	"You're making a real difference by starting your day with such purpose and thoughtful contributions, shaping a better future for yourself and all around you.",
}

// Daily_Sunlight is a collection of friendly messages encouraging sunlight exposure and movement.
var Daily_Sunlight = []string{
	"Time for a little sunshine! Step outside, breathe deep, and let the light energize you for a truly great day.",
	"Feeling that fresh air? A quick walk in the sun is perfect for clearing your head and getting those good vibes flowing.",
	"Don't forget your daily dose of daylight! A few minutes outside can make all the difference to your mood and energy.",
	"Stretch those legs and soak up some rays! Moving your body and enjoying the sunlight is a wonderful way to boost your day.",
	"A perfect day for a little outdoor adventure! Even a short stroll can uplift your spirits and refresh your perspective.",
	"Embrace the outdoors! The sun and fresh air are calling, ready to invigorate your mind and body for whatever comes next.",
	"What a lovely day to move! Getting some sunlight and gentle exercise is an excellent recipe for a positive and productive day ahead.",
	"Ready to shine? Step into the sunlight and let it remind you of all the bright possibilities. A little movement helps too!",
	"Your body and mind will thank you for this! A moment in the sun, a little walk – it's the simple things that make a big impact.",
	"Let's get moving and greet the sun! There's something truly special about starting or refreshing your day with natural light and a bit of motion.",
	"Chase that light! A walk outside can reset your focus and bring a fresh perspective to your day.",
	"The world is waiting just beyond your door. A quick outdoor break can do wonders for your energy levels.",
	"Refresh your spirit with some natural light and movement. It's a simple pleasure that makes a big difference.",
	"Step into the day with purpose and a little sun. It's amazing how much brighter things look outside.",
	"Take a moment to connect with nature. A short walk in the sunlight is great for your well-being.",
	"Getting outside isn't just good for your body; it's fantastic for your mind too. Enjoy the daylight!",
	"A breath of fresh air and a glimpse of the sky can turn your day around. Go for it!",
	"Make a point to enjoy the sunlight today. Even a few minutes can uplift your mood and inspire clarity.",
	"Find your rhythm in the great outdoors. Moving in the sunlight is a wonderful way to invigorate yourself.",
	"Let the natural world inspire you. A simple walk outside can spark creativity and reduce stress.",
	"It's a beautiful day to move your body and enjoy the warmth of the sun. Seize the moment!",
	"Give yourself the gift of outdoor time. Sunlight and movement are powerful tools for a happy, healthy day.",
	"Discover the joy of being active under the open sky. Every step in the sun is a step towards feeling great.",
	"There's a natural boost waiting for you outside. Embrace the sun and movement for an instant pick-me-up.",
	"Start (or continue) your day with the best nature has to offer: light and activity. You deserve it!",
}

// Daily_Exercise is a collection of friendly messages encouraging physical activity and well-being.
var Daily_Exercise = []string{
	"Time to move your body! Walk, run, HIIT, lift — whatever gets you going. Even a short burst can make a difference.",
	"Feeling great starts with moving great! Your daily dose of exercise is a powerful step towards a healthier you.",
	"Don't forget to get your heart rate up today! A little effort goes a long way in boosting your energy and mood.",
	"Challenge yourself today! Whether it's a new routine or an old favorite, every movement counts towards your strength.",
	"A perfect day to break a sweat! Physical activity is a fantastic way to clear your mind and energize your body.",
	"Embrace the burn! Your dedication to exercise is building a stronger, more resilient you, inside and out.",
	"What a fantastic day to get active! Your commitment to daily exercise is truly inspiring and beneficial.",
	"Ready to feel powerful? Step into your workout with purpose and let the endorphins do their magic for a positive day.",
	"Your body and mind will thank you for this movement! It's the simple act of exercising that creates big, lasting impacts.",
	"Let's get stronger and healthier! There's something truly special about pushing your limits and feeling accomplished after a workout.",
	"Every rep, every step, every stretch is progress. Keep going, you're doing amazing things for your health!",
	"Make today an active day! Your consistency in exercising is the key to unlocking sustained energy and well-being.",
	"Refresh your spirit with some movement today. A good workout can be the perfect way to recharge and refocus.",
	"Step into your power! Your dedication to exercise is a testament to your strength and commitment to yourself.",
	"Take a moment to move consciously. Whether it's yoga, dancing, or a brisk walk, engage your body and mind.",
	"Getting active isn't just good for your body; it's fantastic for your mental clarity and stress relief too. Enjoy your workout!",
	"A surge of energy and a sense of accomplishment are just a workout away. Go for it and feel the difference!",
	"Make a point to celebrate your body's capabilities today. Every exercise session is a step towards greater vitality and strength.",
	"Find your rhythm in your workout. Moving your body with intention is a wonderful way to invigorate yourself and build discipline.",
	"Let your physical activity inspire you. A great exercise session can spark creativity and boost your overall outlook.",
	"It's a beautiful day to push your limits and feel the strength within you. Seize the moment and embrace your workout!",
	"Give yourself the gift of fitness today. Exercise is a powerful tool for a happy, healthy, and energized life.",
	"Discover the joy of challenging your body. Every workout is a journey towards becoming a stronger, more capable you.",
	"There's a natural boost waiting for you in every active moment. Embrace exercise for an instant pick-me-up and long-term gains.",
	"Start (or continue) your day with the best you can offer yourself: dedicated movement and physical challenge. You deserve to feel great!",
}

// Daily_Meal is a collection of friendly messages encouraging healthy eating and mindful nourishment.
var Daily_Meal = []string{
	"Fuel your body right! Your next meal is a chance to nourish yourself and power through your day.",
	"Mindful eating matters. Take a moment to appreciate the flavors and nutrients in your food.",
	"Choose wisely, feel amazing! Every healthy meal brings you closer to your best self.",
	"A delicious opportunity to refuel! Enjoy your meal and let it energize your mind and body.",
	"Nourish to flourish! What you eat today supports your energy, focus, and well-being.",
	"Eat well, live well. Making healthy choices at mealtime is a gift you give yourself.",
	"Your plate, your power. Fill it with goodness to conquer the day ahead!",
	"Savor every bite! Mindful eating can transform your meal into a moment of calm and pleasure.",
	"Think fresh, feel fantastic! Opting for wholesome ingredients makes a world of difference.",
	"Hydration and nutrition, a winning combination! Don't forget your water with your wonderful meal.",
	"Plan your plates, elevate your day. A little meal prep goes a long way in healthy eating.",
	"Listen to your body. Give it the fuel it needs to thrive and keep you feeling great.",
	"Cooking with love, eating with joy. Food is more than fuel; it's an experience.",
	"A balanced meal is a happy meal! Strive for variety to get all the nutrients you need.",
	"Your well-being starts on your plate. Make choices that make you feel vibrant and strong.",
	"From farm to fork, appreciate your food. Every meal is a journey of nourishment.",
	"Don't skip! Regular, balanced meals are essential for sustained energy and focus.",
	"Experiment with healthy flavors! Discover new ways to make nutritious meals exciting.",
	"Eating mindfully helps you stay connected with your body's hunger and fullness cues.",
	"Celebrate good food! Healthy eating doesn't mean boring; it means delicious and beneficial.",
	"Treat your body like a temple. Provide it with the best fuel to perform at its peak.",
	"Every ingredient tells a story. Choose ones that contribute positively to your health narrative.",
	"The best investment? Your health! And healthy meals are a huge part of that.",
	"Refuel with intention. Your next meal is an opportunity to boost your energy and mood.",
	"Enjoy your delicious and nutritious meal! It's laying the groundwork for an amazing day.",
}

// Daily_Goal is a collection of friendly messages encouraging goal setting and achievement.
var Daily_Personal = []string{
	"What's your one big goal today? Focus and conquer it! Small steps lead to giant leaps.",
	"Set an intention for today! Even a tiny goal achieved builds momentum and confidence.",
	"Your daily goals are the building blocks of your dreams. Start laying them down with purpose!",
	"Ready to make today count? Break down your main objective into actionable steps and get started.",
	"A focused mind achieves great things. What's the one thing you'll absolutely complete today?",
	"Embrace the challenge of your daily goals! Every task completed is a victory to celebrate.",
	"What a fantastic day to make progress! Your commitment to your goals is inspiring.",
	"Ready to shine? Tackle your most important task first and feel the power of early achievement.",
	"Your efforts towards your goals today will create the future you desire. Keep pushing!",
	"Let's get productive! There's something truly rewarding about setting clear goals and watching them materialize.",
	"Every task you complete, no matter how small, moves you closer to your big vision. Keep at it!",
	"Make today a day of accomplishment! Your consistency in working towards your goals is your superpower.",
	"Refresh your focus on what truly matters today. A clear goal brings clarity to your actions.",
	"Step into your power! Your dedication to achieving your daily goals is a testament to your drive and determination.",
	"Take a moment to define your objective. A well-defined goal is already half-achieved.",
	"Achieving goals isn't just good for your productivity; it's fantastic for your self-esteem and motivation too. Enjoy the process!",
	"A surge of motivation and a sense of accomplishment are just a goal away. Go for it and feel the difference!",
	"Make a point to celebrate your progress today. Every step towards your goal is a win worth acknowledging.",
	"Find your rhythm in goal pursuit. Moving with intention towards your objectives is a wonderful way to build discipline and success.",
	"Let your daily goals inspire you. Completing tasks can spark creativity and boost your overall outlook.",
	"It's a beautiful day to push your limits and feel the strength of your focus. Seize the moment and embrace your objectives!",
	"Give yourself the gift of clarity today. A clear goal is a powerful tool for a productive, fulfilling day.",
	"Discover the joy of checking off tasks. Every completed goal is a journey towards becoming a more capable, effective you.",
	"There's a natural boost waiting for you in every successful action. Embrace your goals for instant satisfaction and long-term achievement.",
	"Start (or continue) your day with the best you can offer yourself: dedicated focus and commitment to your goals. You're unstoppable!",
}
