package bot

import (
	"agent-care-tg/models"
	"log/slog"
	"time"
)

var feedbackMap = map[models.TaskTag][]string{
	models.TagMorning:  dailyMorning,
	models.TagSunlight: dailySunlight,
	models.TagExercise: dailyExercise,
	models.TagMeal:     dailyMeal,
	models.TagPersonal: dailyPersonal,
}

func GetFeedbackMessage(taskTag models.TaskTag) string {
	slog.Info("GetFeedbackMessage", "taskTag", taskTag)
	messages, ok := feedbackMap[taskTag]
	if !ok || len(messages) == 0 {
		return "Great Job, another win in the books!"
	}

	idx := time.Now().Day()

	return messages[idx]
}

var dailyMorning = []string{
	"Routine complete. You’ve already won the first battle of the day, and that momentum is going to carry you through everything else.",
	"That’s one successful morning in the books. You didn’t just wake up; you showed up for yourself, and that makes all the difference.",
	"The hard part is over. You’ve set the tone for the rest of your day by choosing discipline over comfort before the world even started.",
	"You’ve officially started your day on your own terms. That sense of accomplishment you feel right now? Hold onto it as you move forward.",
	"Great job finishing your morning routine. Consistency isn't about being perfect; it's about doing exactly what you just did, day after day.",
	"You’ve given yourself the best possible start. By checking off those morning habits, you’re building a version of yourself that can handle anything.",
	"The morning win is yours. You’ve prioritized your well-being and growth, and the rest of your day will be better because of it.",
	"Routine done. You’ve reclaimed your morning and proved to yourself that you're in control. Now, go out there and keep that energy going.",
	"You didn't hit snooze on your life today. You finished your routine, and that quiet discipline is exactly how big changes are made.",
	"That’s how it’s done. You’ve invested in yourself this morning, and that’s an investment that will pay off in focus and clarity all day long.",
	"Morning routine: complete. You’re not just going through the motions; you’re building a foundation for a life you’re proud of.",
	"You’ve already accomplished more than most people will before noon. Take a second to appreciate the fact that you followed through.",
	"The hardest step is the first one, and you’ve already taken a dozen. You’re officially ahead of the game and ready for whatever comes next.",
	"You’ve successfully navigated your morning. That small victory is a powerful reminder that you have the discipline to reach your bigger goals.",
	"Morning habits finished. You’ve cleared the path for a productive day by taking care of the most important person first: you.",
	"You’ve set the standard for your day by completing your routine. Keep that same intentionality as you move into your next task.",
	"Well done on finishing your morning habits. You’ve proven that you can keep the promises you make to yourself, and that’s true strength.",
	"The momentum is on your side now. You’ve finished your routine and reminded yourself that you’re capable of consistency and focus.",
	"You’ve already done the work that sets the stage for success. Carry this feeling of accomplishment with you into the rest of your morning.",
	"Routine complete. You’ve given your future self a head start today. That’s a win that no one can take away from you.",
	"You’ve mastered your morning. By finishing your routine, you’ve silenced the excuses and chosen progress. Let’s keep that streak alive.",
	"That’s another morning routine in the bag. Every time you finish these habits, you’re strengthening the discipline that changes lives.",
	"You’ve officially started your day with a win. Completing your routine is a clear signal to yourself that your goals are worth the effort.",
	"Great work finishing your morning habits. You’ve created a pocket of peace and productivity that will support you for the next twelve hours.",
	"Routine finished. You’ve started your day with intention and action. That’s a powerful combination that’s going to make today great.",
	"You’ve earned this feeling of accomplishment. Every habit completed is a step closer to the life you envision.",
	"Another morning, another routine mastered. You’re building an unshakeable foundation for success, one intentional action at a time.",
	"Well done on your morning discipline. That commitment to yourself is a beacon, guiding you through the challenges of the day.",
	"You’ve successfully tuned into your inner rhythm. This focused start is your secret weapon for a productive and fulfilling day.",
	"Fantastic effort on your morning routine. You’ve cultivated mental clarity and physical readiness, setting a high bar for today’s achievements.",
	"Your morning win streak continues! This dedication to self-care and preparation is truly inspiring. Keep soaring!",
}

var dailySunlight = []string{
	"Sunlight exposure complete. You’ve just given your circadian rhythm the signal it needs to keep your energy and mood stable all day.",
	"Great job getting outside. That blast of fresh air and natural light is one of the simplest, most effective ways to reset your focus.",
	"Habit finished. You’ve stepped out of the bubble and reconnected with the world, and your brain is going to thank you for the clarity.",
	"You’ve successfully logged your sunlight. It’s a small act, but the biological impact on your sleep and mood is massive. Keep it up.",
	"Fresh air and sunlight: done. You’ve prioritized your biology today, ensuring you stay alert now and sleep better later tonight.",
	"Well done on getting your daily dose of light. Even a few minutes outside makes a world of difference for your mental health and energy.",
	"You’ve cleared your head and soaked up some rays. That intentional break outside is exactly what keeps burnout at bay.",
	"Sunlight habit complete. You’ve just checked off a fundamental pillar of health that most people overlook. You’re doing great.",
	"That’s how you start a momentum shift. A quick step outside into the light is the perfect way to recalibrate your day.",
	"You’ve officially caught some daylight. By making time for the outdoors, you’ve given yourself a natural boost that no caffeine can match.",
	"Outdoor time: finished. You’ve breathed in the fresh air and reset your perspective, which is a win for both your body and mind.",
	"Great work following through on your sunlight habit. You’ve just invested in a better mood and sharper focus for the hours ahead.",
	"You’ve successfully prioritized movement and light. That simple connection with the outdoors is a powerful tool for staying grounded.",
	"Sunlight and fresh air logged. You’ve given your system the natural cues it needs to function at its best today. Well done.",
	"You’ve completed your outdoor habit. That intentional shift in environment is a major win for your productivity and mental clarity.",
	"Nice job stepping into the light. You’ve reminded your body that it’s time to be awake and focused, and you’ll feel the benefit all day.",
	"Habit complete. You’ve traded the screen for the sky for a few minutes, and that mental reset is going to carry you through your next task.",
	"You’ve officially secured your daily sunlight. It’s these small, consistent choices that build a foundation of long-term well-being.",
	"Well done on getting outside. You’ve refreshed your lungs and your outlook, and that energy is going to serve you well for the rest of the day.",
	"Sunlight exposure: done. You’ve taken a proactive step for your health that pays off in better sleep, better mood, and better focus.",
	"You’ve successfully finished your outdoor routine. Never underestimate the power of a few minutes in the sun to turn your day around.",
	"That’s another sunlight win in the books. You’re building the habits of someone who cares about their vitality and mental health.",
	"Great work on getting that fresh air. You’ve stepped away from the noise and recharged your battery with the best fuel available: nature.",
	"Sunlight habit finished. You’ve aligned your internal clock with the day, setting yourself up for peak performance and a restful night.",
	"You’ve officially conquered the outdoor habit. That combination of light and air is the ultimate recipe for a clear head and a steady mood.",
	"The fresh air clear-out is complete. You've swept away mental cobwebs and invited in a wave of new energy for whatever comes next.",
	"You've honored your body's need for natural light. That simple act is a powerful stimulant for mood, sleep, and overall vitality.",
	"Daily dose of nature secured. You've taken a moment to ground yourself, which will anchor your focus and calm throughout the day.",
	"Another successful reconnection with the outside world. This habit is your secret weapon for sustained clarity and a brighter outlook.",
	"Your system is re-calibrated. By stepping into the light, you've optimized your internal clock for peak performance and restful nights.",
	"Well done catching those rays! You've infused your day with a natural energy boost, proving small habits make a huge difference.",
}

var dailyExercise = []string{
	"Workout complete. You’ve just given your body the movement it needs to stay strong, and your brain is going to love the endorphin rush.",
	"Great job finishing your exercise. You pushed through the resistance and chose growth, and that discipline is going to serve you all day.",
	"Habit finished. You’ve officially invested in your future health and current energy levels. That’s a massive win for your well-being.",
	"You’ve successfully logged your workout. It’s not just about the sweat; it’s about the fact that you showed up and did the work. Well done.",
	"Exercise done. You’ve cleared the mental fog and strengthened your body. Carry that feeling of capability into everything else you do today.",
	"Well done on completing your physical activity. You’ve proven once again that you have the power to prioritize what matters most.",
	"You’ve finished your training. That intentional challenge is exactly what builds resilience, both in the gym and in life.",
	"Training session complete. You’ve just checked off one of the most important tasks for your long-term health. Keep that momentum going.",
	"That’s how you build a better version of yourself. You didn't just think about it; you did it. Great work on finishing your exercise.",
	"You’ve officially crushed your workout. By choosing movement, you’ve given yourself a natural advantage in focus, mood, and energy.",
	"Workout finished. You’ve breathed deep, moved well, and reset your system. You’re officially ready for whatever the day throws at you.",
	"Great work following through on your exercise habit. You’ve just proven to yourself that you can handle hard things, one rep at a time.",
	"You’ve successfully prioritized your physical health. That consistent effort is the secret sauce to feeling and performing your best.",
	"Movement habit logged. You’ve given your body the signal that it’s time to be strong and alert. You’re doing an incredible job.",
	"You’ve completed your workout. That sense of accomplishment you feel right now is the direct result of your own discipline and effort.",
	"Nice job finishing your exercise. You’ve traded comfort for progress, and that’s a trade that will always pay off in the long run.",
	"Habit complete. You’ve moved your body and cleared your mind. That mental reset is going to make your next few hours much more productive.",
	"You’ve officially secured your daily exercise win. It’s these quiet victories that add up to a life of health and vitality.",
	"Well done on pushing through your workout. You’ve refreshed your energy and strengthened your resolve. Let’s keep this energy alive.",
	"Exercise: done. You’ve taken a proactive step for your longevity and mental clarity. That’s a win you should be proud of.",
	"You’ve successfully finished your training routine. Never underestimate the power of a good workout to shift your entire perspective.",
	"That’s another exercise win in the books. You’re building the habits of someone who takes ownership of their health and performance.",
	"Great work on completing your physical challenge. You’ve stepped up and done what most people only talk about doing.",
	"Exercise habit finished. You’ve primed your body for peak performance and your mind for steady focus. You’re crushing it.",
	"You’ve officially conquered your daily movement. That combination of effort and consistency is the fastest way to reach your goals.",
	"Your workout is complete. You’ve proven your dedication to your physical well-being, building strength and resilience with every effort.",
	"Great job on that exercise session! You've fueled your body with movement and your mind with focus. Carry that momentum into your day.",
	"Another victory for your health! You’ve pushed your limits and invested in a stronger, more capable you. That's true progress.",
	"Exercise done. You've cleared the mental fog and generated powerful endorphins. You're now physically and mentally primed for success.",
	"Well done maintaining your commitment to fitness. Every rep and every step builds unwavering discipline and self-confidence.",
	"You've conquered another physical challenge. This consistency is not just about muscle, it’s about building an unbreakable spirit.",
}

var dailyMeal = []string{
	"Meal complete. You’ve just given your body the high-quality fuel it needs to keep your energy stable and your mind sharp.",
	"Great job choosing a healthy meal. You’ve prioritized your long-term well-being over a quick craving, and that discipline is a huge win.",
	"Habit finished. You’ve successfully nourished your system with the right nutrients, and you’re going to feel the benefit in your focus all afternoon.",
	"You’ve successfully logged your healthy meal. By choosing quality ingredients, you’re showing yourself the respect your body deserves. Well done.",
	"Nourishment done. You’ve fueled your cells and cleared the path for sustained energy. Carry that sense of vitality into your next task.",
	"Well done on completing your mindful meal. You’ve proven that you can make intentional choices even in the middle of a busy day.",
	"You’ve finished your meal with intention. That conscious choice to eat well is exactly what builds a foundation of health and performance.",
	"Healthy meal complete. You’ve just checked off one of the most important habits for your metabolic health. Keep that momentum going.",
	"That’s how you fuel a high-performer. You didn't just eat; you nourished yourself. Great work on finishing your meal habit.",
	"You’ve officially fueled up the right way. By choosing nutrient-dense food, you’ve given yourself a natural advantage in brainpower and mood.",
	"Meal finished. You’ve fed your body well and reset your energy. You’re officially prepared to handle the rest of your day with clarity.",
	"Great work following through on your healthy eating habit. You’ve just proven to yourself that you can prioritize your health, one plate at a time.",
	"You’ve successfully prioritized your nutrition. That consistent effort to eat well is the secret to maintaining your edge and feeling great.",
	"Healthy eating habit logged. You’ve given your body the nutrients it needs to thrive and stay resilient. You’re doing an incredible job.",
	"You’ve completed your mindful meal. That sense of feeling satisfied and energized is the direct result of your own intentional choices.",
	"Nice job finishing your healthy meal. You’ve traded convenience for quality, and that’s a trade that will always pay off in how you feel.",
	"Habit complete. You’ve nourished your body and avoided the energy crash. That steady focus is going to make your afternoon much more productive.",
	"You’ve officially secured your daily nutrition win. It’s these small, consistent choices that build a life of health and longevity.",
	"Well done on choosing a balanced meal. You’ve refreshed your energy and strengthened your commitment to your health goals.",
	"Healthy meal: done. You’ve taken a proactive step for your vitality and mental performance. That’s a win you should be proud of.",
	"You’ve successfully finished your mindful eating routine. Never underestimate the power of a good meal to stabilize your mood and focus.",
	"That’s another nutrition win in the books. You’re building the habits of someone who takes ownership of their fuel and their future.",
	"Great work on completing your healthy eating goal. You’ve stepped up and made a choice that your future self will thank you for.",
	"Meal habit finished. You’ve primed your system for peak energy and your mind for steady concentration. You’re crushing it.",
	"You’ve officially conquered your daily nutrition. That combination of quality and intention is the fastest way to feel your absolute best.",
	"Super! You’ve consciously nourished your body, providing the high-quality fuel it needs for sustained energy and sharp mental performance.",
	"Great job on your mindful eating. This intentional choice reinforces your commitment to long-term health and vitality.",
	"You’ve successfully fueled your system with optimal nutrients. Expect increased clarity and focus as your body thrives.",
	"Healthy eating logged. Each deliberate meal strengthens your well-being and empowers you to perform at your best.",
	"Nourishment done. You’ve treated your body with the respect it deserves, setting a powerful example for sustained self-care.",
	"Well done on your nutrition choice! This consistent effort creates a strong foundation for your energy, mood, and overall health.",
}

var dailyPersonal = []string{
	"Goal complete. You’ve just proven to yourself that your focus is stronger than your distractions, and that’s a massive win.",
	"Great job finishing your personal objective. You set a target and hit it, and that kind of follow-through is exactly how big dreams become reality.",
	"Habit finished. You’ve successfully moved the needle on what matters most to you, and that progress is going to fuel your next big win.",
	"You’ve successfully logged your goal completion. By staying disciplined and focused, you’re building a version of yourself that can achieve anything.",
	"Objective done. You’ve cleared a major hurdle today and proved that you’re in control of your time and energy. Well done.",
	"Well done on completing your important task. You’ve prioritized progress over procrastination, and you’re going to feel the benefit in your confidence all day.",
	"You’ve finished your deep work. That intentional effort is exactly what separates the dreamers from the achievers. Keep that same energy.",
	"Personal goal complete. You’ve just checked off a task that brings you one step closer to your vision. Keep that momentum going.",
	"That’s how you build a life of purpose. You didn't just talk about it; you did it. Great work on finishing your personal habit.",
	"You’ve officially crushed your goal. By choosing to focus on what’s important, you’ve given yourself a natural advantage in productivity and satisfaction.",
	"Task finished. You’ve put in the work and achieved the result. You’re officially one step further along your path than you were this morning.",
	"Great work following through on your personal objective. You’ve just proven to yourself that you can handle complex tasks with clarity and resolve.",
	"You’ve successfully prioritized your own growth. That consistent effort to reach your goals is the secret to building a life you’re truly proud of.",
	"Personal habit logged. You’ve given yourself the gift of accomplishment and the proof that you can do exactly what you set out to do.",
	"You’ve completed your goal. That sense of satisfaction you feel right now is the direct reward for your own discipline and hard work.",
	"Nice job finishing your important task. You’ve traded minor distractions for major progress, and that’s a trade that will always pay off.",
	"Habit complete. You’ve tackled your objective and cleared your plate. That mental space is going to make your next few hours much more focused.",
	"You’ve officially secured your daily personal win. It’s these small, consistent victories that add up to a life of extraordinary achievement.",
	"Well done on pushing through to the finish line. You’ve refreshed your momentum and strengthened your resolve. Let’s keep this streak alive.",
	"Goal: done. You’ve taken a proactive step for your future and your own self-respect. That’s a win you should be proud of.",
	"You’ve successfully finished your deep work session. Never underestimate the power of a single completed goal to shift your entire day’s trajectory.",
	"That’s another personal win in the books. You’re building the habits of someone who takes ownership of their time and their outcomes.",
	"Great work on completing your personal challenge. You’ve stepped up and done the work that actually moves the needle for you.",
	"Objective habit finished. You’ve primed your mind for even bigger successes and proved that you have what it takes to follow through.",
	"You’ve officially conquered your daily goal. That combination of focus and action is the fastest way to turn your ambitions into reality.",
	"Personal goal achieved! You’ve demonstrated incredible focus and resolve. This progress fuels your journey towards even greater accomplishments.",
	"Your consistent effort in moving the needle on what matters most is truly commendable.",
	"Another victory for your purpose! You’ve prioritized meaningful action, building a life of intention, one successful task at a time.",
	"Objective done. You’ve proven your ability to overcome distractions and complete tasks that contribute to your larger vision.",
	"Well done maintaining your commitment to personal growth. This discipline is the bedrock of lasting change and profound achievement.",
	"You’ve successfully pushed your boundaries. Every personal win like this strengthens your confidence and expands what you believe is possible.",
}
